### ISSUE TITLE
Preserve non-AssetBundle files in StreamingAssets

### ISSUE THREAD

**Issue by linojon** [Unity-Technologies/AssetBundles-Browser#112]
We use Assets/StreamingAssets/ for more than bundled assets. When both Copy to StreamingAssets and Clear Folders are checked my non-Asset Bundle files are also "cleared". Please don't :)

**Comment by alffanclub** [comment]
The build script is intended to be a model that users can customize as many users will need something more specific than what we can provide.  My suggestion is you edit the build code to make the "copy to streaming assets" build to something like "Assets/StreamingAssets/MyBundles" instead of to the root of StreamingAssets.  Look in AssetBundleBuildTab.cs and the varialbe m_streamingPath.

**Comment by alffanclub** [comment]
One more note, you can build directly to streaming assets, rather than building to another location then copying to SA.  so you could do that through the UI without any code changes.
