### ISSUE TITLE
Error inspecting second asset bundle

### ISSUE THREAD

**Issue by Tyrannicus100BC** [Unity-Technologies/AssetBundles-Browser#2]
I seam to have a 100% repro, pretty fatal error.

After I build bundles, I go to the Inspect tab. Selecting the first bundle correctly shows its contents. However, when I click on a second bundle, I get this fatal error repeated multiple times:

"The AssetBundle xxx can't be loaded because another AssetBundle with the same files is already loaded"

I am using Unity 5.6.0b8, AssetBundles-Browser hash d0f494d9fe412636a1c146a0f56ea8854fbb26a9, and the hack for GetRowsFromIDs I mentioned in Issue #1.

I have attached a screen shot, video, and sample project (video is inside sample project.

![inspecterror](https://cloud.githubusercontent.com/assets/4694537/23044915/380753de-f457-11e6-9cf4-4317ddc456b9.png)

[BundledSheets.zip](https://github.com/Unity-Technologies/AssetBundles-Browser/files/781747/BundledSheets.zip)

**Comment by alffanclub** [comment]
Hi, for the time being we've had to pull the Inspect part of the browser.  This error has to do with how Unity loads and manages bundles. We are currently hunting for a way to bring the inspect option back, but since it was not functional, we wanted to pull it while doing a refresh of the other pieces.  Thanks for your feedback, and I'm hoping we'll have Inspect back online soon.
