### ISSUE TITLE
AssetBundleBrowser: Bundle name 'assets$resources$cube.prefab' contains a period.  

### ISSUE THREAD

**Issue by optimisez** [Unity-Technologies/AssetBundles-Browser#30]
AssetBundleBrowser: Bundle name 'assets$resources$cube.prefab' contains a period.  Internally Unity keeps 'bundleName' and 'variantName' separate, but externally treat them as 'bundleName.variantName'.  If a bundleName contains a period, the build will (probably) succeed, but this tool cannot tell which portion is bundle and which portion is variant.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

My workflow needs to create the asset bundle with the period that will show the full path so I can directly understand the root content of the asset bundle. I hope this fix bug can be fixed so that I can use this tool to see the details of the asset bundle

**Comment by alffanclub** [comment]
@optimisez do you ever use variants? I could maybe work out a way for you to mark items with periods as "not a variant" but I'm not sure how stable that would be. Is there a particular reason you don't just do an alternate character, such as "cube_prefab"?  
One unrelated note, I noticed your bundle name has $ where the file has folders, just fyi you can mimic folder structure in bundles. You could name the bundle "assets/resources/cube_prefab".  In the browser, it would show as a file hierarchy, and on-disk the generated cube_prefab bundle would be in a folder called resources in a folder called assets. Not sure if that would be beneficial, just making sure you were aware.
Thanks for bringing up the issue.  I'll start pondering and poking at some way to allow periods in bundle names.

**Comment by optimisez** [comment]
I would like to variants but until now I still not really sure how to use it. The reason I not able to use alternate character, such as "cube_prefab" is because I already designed the APIs to load asset bundle and its asset that way and I think using period can clearly tell that it is file extension. 
For bundle naming, unfortunately file name does not allow / symbol. I use $ symbol to replace / symbol. So, name the bundle "assets/resources/cube_prefab" is not possible.

**Comment by alffanclub** [comment]
to be clear, I was not suggesting you build a bundle, then rename it to include a / in the file name. If you create a bundle named "assets/whatever" in editor, then the build code will create a folder called "assets" and then create a bundle called "whatever" and put it in there. You can then load that bundle as "assets/whatever". In the bundle browser, it will visually display this as a sub folder in the bundle list. The asset list of the browser will mark that asset as being in a bundle called "assets/whatever" as will the old in-inspector bundle drop down. 
As to the original topic, using a period in a bundle name, I just can't support it. I understand you wanting to know about file extensions, but that just doesn't really translate into bundles. Partly due to the fact that the variant system has chosen to hijack extensions and use them as variants. Partly due to the fact that the bundle is not the asset you started with. It is a bundle of it. It wouldn't make sense to have a file called "myCool.doc" that is your word doc, then another file somewhere else called "myCool.doc" that is a zip file containing your doc. The zip should be called myCoolDoc.zip" or something along those lines. 
One other note, if you are really putting your assets in your project in a folder called "resources", then they will show up in the player build automatically. (see https://unity3d.com/learn/tutorials/temas/best-practices/resources-folder). This means that if you have some asset that traces it's file path up to any folder called "resources" any distance up the path, AND you mark it as being in a bundle, you'll end up with that asset both in a bundle, and in the player build.

**Comment by alffanclub** [comment]
@optimisez  I should add one more note. It's exactly these sorts of uncommon usage patterns that led us to making this tool open source. We know there's no possible way for us to make a tool that suits everyone's workflow perfectly. If you have a workflow that you need to follow to be productive, then I don't want to interfere with that. Please take the tool and customize it to your hearts content. If you find a way to cleanly and safely support periods in bundle names and variants feel free to create a PR to bring it back to the masses. More likely I'd imagine you could fairly easily customize the tool to your need. The changes needed probably couldn't be translated back into a general-purpose solution, but that is fine.  That's even encouraged. We expect more than one situation to arise that requires the user to take our tool, customize it in a very specialized way, and use it for just their own project. 
Hope that helps, and thanks for trying out this tool.
