### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by altaf-navalur** [Unity-Technologies/AssetBundles-Browser#4]
Hi,
 I get this & other compiler errors,

Assets/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleIssuesWindow.cs(26,21): error CS0122: `UnityEditor.IMGUI.Controls.TreeView' is inaccessible due to its protection level

I am using Unity 5.5.1f1 on Windows 10 & my platform is Android.

**Comment by alffanclub** [comment]
Thanks for the feedback.  This should be gone in the newest version.

**Comment by JackyCBN** [comment]
I clone this today.
It still also get this compiler errors
Assets/Editor/AssetBundleBrowser/AssetBundleModel/ABModelAssetInfo.cs(10,36): error CS0122: `UnityEditor.IMGUI.Controls.TreeViewItem' is inaccessible due to its protection level

I am also using Unity 5.5.1p2(64bit) on Windows 7 & my platform is Android.

**Comment by alffanclub** [comment]
Hi JackyCBN, thanks for reaching out and including all those great details. The TreeView was a new feature in 5.6, which this tool relies on. So you have to have 5.6 to run this tool.  When you are able, please update to 5.6, and if you still have issues, feel free to reach out again. 
Thanks!
