### ISSUE TITLE
Namespace Conflict

### ISSUE THREAD

**Issue by Guxin233** [Unity-Technologies/AssetBundles-Browser#88]
I want to use AssetBundles-Browser tool in my Unity project. When I import this folder into project asset folder and open any script in Visual Studio, it alert an error that MyProjectName.Editor namespace has already exist ( I have some script file in Asset/Editor folder). How should I approach this problem?

**Comment by alffanclub** [comment]
Hi @Guxin233 
Most likely the issue has to do with your version of "Visual Studio Tools for Unity" or Unity itself and their conflict with the use of .asmdef files. I can think of two solutions...
1.  If you are on 2018.1 or newer, use the package version from the package manager. That would install the package instead of you having to get the code directly from github.
2.  If you want the code (no matter what version of Unity you are on), pull down the github repo, then delete Editor/Unity.AssetBundleBrowser.Editor.asmdef from the project. 

If neither of those work, it may be an issue of how you arrange your folders, but from what I've run into it should just work regardless of that arrangement.

Let me know how this goes.
-Bill

**Comment by Guxin233** [comment]
finally I import this plugin from Unity assetstore page (instead of from Github) , and the namespace is "UnityEngine.AssetBundles". So the namespace conflict problem has been solved !
